<a href="https://colab.research.google.com/github/erdijova/scikit-learn-cookbook/blob/main/1_Common_Conventions_and_API_Elements_of_scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Introduction to scikit-learn’s design philosophy

scikit-learn’s design is centered around a few core principles: consistency, simplicity, modularity, and
reusability. At its foundation, scikit-learn offers a unified interface for a broad range of ML algorithms,
where most models follow a similar pattern: they use fit() to train the model, predict() to
make predictions, and transform() to manipulate data. This consistency allows users to easily
switch between models, improving productivity and reducing the learning curve.

**Understanding estimators**

In [1]:
from sklearn.linear_model import LinearRegression
import numpy as np
# Example data
X = np.array([[1], [2], [3], [4], [5]]) # Feature matrix
y = np.array([1, 2, 3, 3.5, 5]) # Target values
# Create and fit the model
model = LinearRegression()
model.fit(X, y)
# Predict values for new data
X_new = np.array([[6], [7]])
predictions = model.predict(X_new)
print(predictions)

[5.75 6.7 ]


The library also provides a nice shortcut method, fit_predict(), that combines these operations
into a single API call—a very useful tool! Now, there is a reason why scikit-learn has both the fit()
and predict() methods separate, as well as fit_predict(). Typically, the fit_predict()
method is applied when you want to obtain predictions within the same dataset the model was trained
on.

In [2]:
# Fit_predict is not used in LinearRegression,
# but as an example for clustering:
from sklearn.cluster import KMeans
# Example data
X = np.array([[1], [2], [3], [4], [5]])
# KMeans Clustering example
kmeans = KMeans(n_clusters=2)
labels = kmeans.fit_predict(X)
print(labels)

[0 0 1 1 1]


scikit-learn’s design ensures that whether you are working with simple linear regression or more
complex algorithms such as random forests, the pattern remains the same, promoting consistency
and ease of use.

### Transformers and the transform() method

In scikit-learn, transformers are tools that modify data by applying transformations such as scaling,
normalization, or encoding to prepare it for modeling. Each transformer follows a consistent interface,
using the fit() method to learn any necessary parameters from the data and the transform()
method to apply those transformations.

In [3]:
from sklearn.preprocessing import StandardScaler
import numpy as np
# Example data
X = np.array([[1, 2], [3, 4], [5, 6]])
# Create a StandardScaler instance
scaler = StandardScaler()
# Fit the scaler on the data
scaler.fit(X)
# Transform the data
X_scaled = scaler.transform(X)
print(X_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


Another common shortcut that we saw previously, fit_transform(), allows users to perform
both steps in one command, making preprocessing workflows more efficient. Again, when to use
fit_transform() and fit() with transform() separately depends on the task at hand.

Remember, our test dataset is meant to be
treated exactly like our training data for model consistency purposes, so implementing a separate
fit() method on it could potentially alter our test data and make our model predictions unreliable
when applied in a real-world scenario:

In [4]:
from sklearn.preprocessing import StandardScaler
import numpy as np
# Example data
X = np.array([[1, 2], [3, 4], [5, 6]])
# Create a StandardScaler instance and
# fit_transform the data in one step
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


This consistency across all transformers allows them to be integrated seamlessly into ML pipelines,
ensuring that the same transformation is applied to both the training and test data, something that
becomes significantly important when implementing production-level models.

### Common attributes and methods

Similarly, methods such as score() allow users to evaluate model performance, typically returning
a default metric such as accuracy for classifiers or R2 for regressors. These common features ensure
consistency across different models and simplify model analysis and interpretation:

In [5]:
from sklearn.linear_model import LinearRegression
import numpy as np
# Example data
X = np.array([[1], [2], [3], [4], [5]]) # Feature matrix
y = np.array([1, 2, 3, 3.5, 5]) # Target values
# Create and fit the model
model = LinearRegression()
model.fit(X, y)
# Access coefficients (slope of the linear model)
print("Coefficients:", model.coef_)
# Access y-intercept
print("Intercept:", model.intercept_)
# Use score() method to evaluate the model (R-squared value)
print("Model R-squared:", model.score(X, y))

Coefficients: [0.95]
Intercept: 0.04999999999999938
Model R-squared: 0.9809782608695652


### Hyperparameter tuning with search methods

Hyperparameter tuning is crucial for optimizing candidate ML models, and scikit-learn makes this
process easier with a variety of built-in search methods. The library provides two popular methods,
GridSearchCV() and RandomizedSearchCV(), in easy-to-implement APIs, along with
their counterpart methods, that implement a successive halving approach to hyperparameter search.

In [6]:
from sklearn.ensemble import RandomForestClassifier
# Create a RandomForestClassifier model
model = RandomForestClassifier()
# Set hyperparameters prior to training using set_params()
model.set_params(n_estimators=100, max_depth=10, random_state=42)
# Check the updated parameters
print(model.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}


As you can see, scikit-learn provides a detailed output of model hyperparameters that provide the
best fit. This is something we can use in our model for training purposes.